spring:
  application:
    name: blogzip-api
  config:
    import:
      - application-domain.yml
      - application-notification.yml
jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-expires-days: 7
oauth2:
  google:
    client-id: 538244264177-f2a956r71n7g6cp1tomqfmcsvdu6nhcp.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config:
    activate:
      on-profile: local
oauth2:
  google:
    redirect-uri: http://localhost:3000/login/google
logging:
  level:
    root: info
selenium:
  chrome-options:
    - "--window-size=1920,1080"

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: warn
oauth2:
  google:
    redirect-uri: https://blogzip.co.kr/login/google
selenium:
  chrome-options:
    - "--headless=new" # 크롬창 노출 x
    - "--window-size=1920,1080"