spring:
  config:
    activate:
      on-profile: test
jwt:
  secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  access-token-expires-days: 1

oauth2:
  google:
    client-id: client-id
    client-secret: client-secret
    redirect-uri: redirect-uri