spring:
  application:
    name: blogzip-api
  module:
    name: api
  config:
    import:
      - application-domain.yml
      - application-notification.yml
      - application-ai.yml
jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-expires-days: 7
oauth2:
  google:
    client-id: 538244264177-f2a956r71n7g6cp1tomqfmcsvdu6nhcp.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config:
    activate:
      on-profile: local
oauth2:
  google:
    redirect-uri: http://localhost:3000/login/google
logging:
  level:
    root: debug

# 크로미움 옵션 모음 : https://peter.sh/experiments/chromium-command-line-switches/
selenium:
  chrome-options:
    - "--window-size=1920,1080"
    - "--keep-alive-for-test" # 마지막 브라우저 창이 닫힌 후에도 브라우저를 계속 유지 (idle 세션 끊는 현상 디버깅)

---
spring:
  config:
    activate:
      on-profile: local-prod
oauth2:
  google:
    redirect-uri: https://blogzip.co.kr/login/google
logging:
  level:
    root: info
selenium:
  chrome-options:
    - "--window-size=1920,1080"
    - "--keep-alive-for-test" # 마지막 브라우저 창이 닫힌 후에도 브라우저를 계속 유지 (idle 세션 끊는 현상 디버깅)

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: warn
oauth2:
  google:
    redirect-uri: https://blogzip.co.kr/login/google
selenium:
  chrome-options:
    - "--headless=new" # 크롬창 노출 x
    - "--window-size=1920,1080"
    - "--keep-alive-for-test" # 마지막 브라우저 창이 닫힌 후에도 브라우저를 계속 유지 (idle 세션 끊는 현상 디버깅)