spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogzip
    username: blogzip
    password: blogzip
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always