spring:
  jpa:
    database: mysql
    open-in-view: false
jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-expires-days: 1
  refresh-token-expires-days: 30

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/blogzip
    username: blogzip
    password: blogzip
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://13.125.138.71:3306/blogzip
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never