spring:
  application:
    name: blogzip-api
  config:
    import:
      - application-domain.yml
      - application-crawler.yml
      - application-notification.yml
jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-expires-days: 7
  refresh-token-expires-days: 30
oauth2:
  google:
    client-id: 538244264177-f2a956r71n7g6cp1tomqfmcsvdu6nhcp.apps.googleusercontent.com
    client-secret: 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
    scope:
      - profile
      - email

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    root: debug
oauth2:
  google:
    redirect-uri: http://localhost:3000/login/google

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: warn
oauth2:
  google:
    redirect-uri: https://blogzip.co.kr/login/google