spring:
  application:
    name: blogzip-api
  config:
    import:
      - application-domain.yml
      - application-crawler.yml
      - application-notification.yml
  profiles:
    active: local
    include: domain

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
