spring:
  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true # 메모리에서 페이징 처리 사전 차단

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/blogzip
    username: blogzip
    password: blogzip
    hikari:
      maximum-pool-size: 10 # 최대 pool 크기
      minimum-idle: 5 # 최소 pool 크기
      idle-timeout: 300000 # 연결위한 최대 유후 시간 (5분)
      max-lifetime: 1800000 # 반납된 커넥션의 최대 수명 (30분, MySQL의 wait_timeout보다 짧게)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: local-prod
  datasource:
    url: jdbc:mysql://13.125.138.71:3306/blogzip
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/blogzip
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never