---
spring:
  config:
    activate:
      on-profile: local
selenium:
  chrome-options:
    - "--window-size=1920,1080"

---
spring:
  config:
    activate:
      on-profile: prod
selenium:
  chrome-options:
    - "--headless=new" # 크롬창 노출 x
    - "--window-size=1920,1080"