spring:
  application:
    name: blogzip-batch
  module:
    name: batch
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      max-lifetime: 1800000  # 30분마다 커넥션 갱신
      keepalive-time: 300000  # 5분마다 커넥션 체크
      connection-test-query: "SELECT 1"
  config:
    import:
      - application-domain.yml
      - application-notification.yml
      - application-logging.yml
      - application-ai.yml
logging:
  level:
    org.hibernate.SQL: info
    io.netty.channel.DefaultChannelPipeline: error
crawler:
  base-url: ${CRAWLER_BASE_URL:http://localhost:8090}

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: local-prod
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: prod
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info
