spring:
  application:
    name: blogzip-batch
  module:
    name: batch
  config:
    import:
      - application-domain.yml
      - application-notification.yml
      - application-logging.yml
      - application-ai.yml
logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

selenium:
  chrome-options:
    - "--window-size=1920,1080"

---
spring:
  config:
    activate:
      on-profile: local-prod
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

selenium:
  chrome-options:
#    - "--headless=new" # 크롬창 노출 x (headless 모드 시 동적으로 url이 변경되는 페이지 대응이 불가하여 비활성화함)
    - "--window-size=1920,1080"

---
spring:
  config:
    activate:
      on-profile: prod
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

selenium:
  chrome-options:
#    - "--headless=new" # 크롬창 노출 x (headless 모드 시 동적으로 url이 변경되는 페이지 대응이 불가하여 비활성화함)
    - "--window-size=1920,1080"