spring:
  application:
    name: blogzip-batch
  config:
    import:
      - application-domain.yml
      - application-notification.yml
open-ai:
  api-key: "${OPEN_AI_API_KEY}"
  assistant-id: "${OPEN_AI_ASSISTANT_ID}"
  thread-id: "${OPEN_AI_THREAD_ID}"
logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

selenium:
  chrome-options:
    - "--window-size=1920,1080"

---
spring:
  config:
    activate:
      on-profile: prod
  batch:
    job:
      summarize:
        retry:
          max-attempts: 3
          backoff-seconds: 300 # 5분
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

selenium:
  chrome-options:
#    - "--headless=new" # 크롬창 노출 x
    - "--window-size=1920,1080"