spring:
  application:
    name: blogzip-batch
  config:
    import:
      - application-domain.yml
      - application-crawler.yml
      - application-notification.yml
open-ai:
  api-key: "${OPEN_AI_API_KEY}"
  assistant-id: "${OPEN_AI_ASSISTANT_ID}"
  thread-id: "${OPEN_AI_THREAD_ID}"

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
      schema-locations:
        - classpath:schema.sql
logging:
  level:
    root: warn