spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  mail:
    host: "smtp.email.ap-chuncheon-1.oci.oraclecloud.com"
    port: 587
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "blogzip"
    from-address: "no-reply@blogzip.co.kr"

---
spring:
  config:
    activate:
      on-profile: local-prod
  mail:
    host: "smtp.email.ap-chuncheon-1.oci.oraclecloud.com"
    port: 587
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "blogzip"
    from-address: "no-reply@blogzip.co.kr"

---
spring:
  config:
    activate:
      on-profile: prod
  mail:
    host: "smtp.email.ap-chuncheon-1.oci.oraclecloud.com"
    port: 587
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "blogzip"
    from-address: "no-reply@blogzip.co.kr"
