spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
aws:
  ses:
    access-key: "${AWS_SES_ACCESS_KEY}"
    secret-key: "${AWS_SES_SECRET_KEY}"

---
spring:
  config:
    activate:
      on-profile: local-prod
aws:
  ses:
    access-key: "${AWS_SES_ACCESS_KEY}"
    secret-key: "${AWS_SES_SECRET_KEY}"

---
spring:
  config:
    activate:
      on-profile: prod
aws:
  ses:
    access-key: "${AWS_SES_ACCESS_KEY}"
    secret-key: "${AWS_SES_SECRET_KEY}"