spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  mail:
    host: "${OCI_EMAIL_SMTP_HOST:}"
    port: "${OCI_EMAIL_SMTP_PORT:587}"
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "${OCI_EMAIL_FROM_NAME:blogzip}"
    from-address: "${OCI_EMAIL_FROM_ADDRESS:no-reply@blogzip.co.kr}"

---
spring:
  config:
    activate:
      on-profile: local-prod
  mail:
    host: "${OCI_EMAIL_SMTP_HOST:}"
    port: "${OCI_EMAIL_SMTP_PORT:587}"
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "${OCI_EMAIL_FROM_NAME:blogzip}"
    from-address: "${OCI_EMAIL_FROM_ADDRESS:no-reply@blogzip.co.kr}"

---
spring:
  config:
    activate:
      on-profile: prod
  mail:
    host: "${OCI_EMAIL_SMTP_HOST:}"
    port: "${OCI_EMAIL_SMTP_PORT:587}"
    username: "${OCI_EMAIL_SMTP_USERNAME:}"
    password: "${OCI_EMAIL_SMTP_PASSWORD:}"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from-name: "${OCI_EMAIL_FROM_NAME:blogzip}"
    from-address: "${OCI_EMAIL_FROM_ADDRESS:no-reply@blogzip.co.kr}"
