name: EC2에 배포

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blogzip
            git pull origin master
            cd api
            ./gradlew clean
            ./gradlew bootRun
            java -jar build/libs/api-0.0.1-SNAPSHOT.jar